driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: centos-6.7

suites:
- name: default
  run_list:
  - recipe[zookeeper-service]
  - recipe[mesos::master]
  - recipe[mesos::slave]
  - recipe[marathon]
  - recipe[marathon::service]
  attributes:
    mesos:
      version: 0.23.0
    marathon:
      master: zk://localhost:2181/mesos
